from typing import Any, Sequence

class Tensor:
    def __init__(
        self,
        data: Any,
        shape: Sequence[int] | None = None,
        requires_grad: bool = False,
    ) -> None: ...

    def cpu(self) -> list[float]: ...
    def shape(self) -> list[int]: ...
    def ndim(self) -> int: ...
    def numel(self) -> int: ...

    def grad(self) -> "Tensor": ...
    def zero_grad(self) -> None: ...
    def backward(self) -> None: ...

    def matmul(self, other: "Tensor") -> "Tensor": ...
    def reshape(self, *shape: int) -> "Tensor": ...
    def flatten(self) -> "Tensor": ...
    def transpose(self) -> "Tensor": ...
    def transpose_last_two_dims(self) -> "Tensor": ...

    def sum(self) -> "Tensor": ...
    def mean(self) -> "Tensor": ...
    def max(self) -> "Tensor": ...
    def sum_to_shape(self, shape: Sequence[int]) -> "Tensor": ...

    def clone(self) -> "Tensor": ...
    def detach(self) -> "Tensor": ...
    def requires_grad_(self, value: bool = True) -> "Tensor": ...

    def relu(self) -> "Tensor": ...
    def softmax(self, dim: int = -1) -> "Tensor": ...
    def cross_entropy(self, target: "Tensor") -> "Tensor": ...
    def bce_with_logits(self, target: "Tensor") -> "Tensor": ...
    def sqrt(self) -> "Tensor": ...

    def __add__(self, other: "Tensor | float") -> "Tensor": ...
    def __radd__(self, other: float) -> "Tensor": ...
    def __sub__(self, other: "Tensor | float") -> "Tensor": ...
    def __rsub__(self, other: float) -> "Tensor": ...
    def __mul__(self, other: "Tensor | float") -> "Tensor": ...
    def __rmul__(self, other: float) -> "Tensor": ...
    def __truediv__(self, other: "Tensor | float") -> "Tensor": ...
    def __rtruediv__(self, other: float) -> "Tensor": ...
    def __matmul__(self, other: "Tensor") -> "Tensor": ...
